value = input('digite algo: ')
print('Qual é o tipo do dado? {}'.format(type(value)))
print('Valor é numérico? {}'.format(value.isnumeric()))
print('Valor é alfabético? {}'.format(value.isalpha()))
print('Valor é alfanumérico? {}'.format(value.isalnum()))
